name: Daily Heatmap Update

on:
  schedule:
    - cron: '0 21 * * *' # Every day at 21:00 UTC (5:00 PM EDT)
  workflow_dispatch:     # Optional manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Generate heatmap
      run: python visual_data.py

    - name: Commit updated heatmap
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add app/index.html
        git commit -m "📈 Daily NASDAQ heatmap update"
        git push
